version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/lighttpd/project/ 
  - source: /conf/project.felipeferreira.net.conf
    destination: /etc/lighttpd/vhosts.d/
permissions:
   - object: /var/www/lighttpd/project/    
     pattern: "**"
     owner: lighttpd
     group: lighttpd
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/beforeinstall.sh
      runas: root  
   AfterInstall:
    - location: scripts/restartserver.sh
      runas: root
