version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/lighttpd/project/    
 hooks:
  BeforeInstall:    
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root
