version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/lighttpd/project/    
permissions:
   - object: /var/www/lighttpd/project/    
     pattern: "**"
     owner: lighttpd
     group: lighttpd
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/beforeinstall.sh
      runas: root
    - location: scripts/startserver.sh
      runas: root
   AfterInstall:
    - location: scripts/restartserver.sh
      runas: root
